//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XGame.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XGame.Domain.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ser maior ou igual a {1}..
        /// </summary>
        public static string A_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1 {
            get {
                return ResourceManager.GetString("A_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados não encontrados..
        /// </summary>
        public static string DADOS_NAO_ENCONTRADOS {
            get {
                return ResourceManager.GetString("DADOS_NAO_ENCONTRADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um {0} chamado {1}..
        /// </summary>
        public static string JA_EXISTE_UM_X0_CHAMADO_X1 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_CHAMADO_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um {0} com a {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UM_X0_COM_A_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_COM_A_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um {0} com o {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UM_X0_COM_O_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UM_X0_COM_O_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma {0} chamada {1}..
        /// </summary>
        public static string JA_EXISTE_UMA_X0_CHAMADA_X1 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UMA_X0_CHAMADA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma {0} com a {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UMA_X0_COM_A_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UMA_X0_COM_A_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma {0} com o {1} {2}.
        /// </summary>
        public static string JA_EXISTE_UMA_X0_COM_O_X1_X2 {
            get {
                return ResourceManager.GetString("JA_EXISTE_UMA_X0_COM_O_X1_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir um {0} associado a um {1}..
        /// </summary>
        public static string NAO_E_POSSIVEL_EXCLUIR_UM_X0_ASSOCIADO_A_UM_X1 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_UM_X0_ASSOCIADO_A_UM_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir um {0} associado a uma {1}..
        /// </summary>
        public static string NAO_E_POSSIVEL_EXCLUIR_UM_X0_ASSOCIADO_A_UMA_X1 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_UM_X0_ASSOCIADO_A_UMA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir uma {0} associada a um {1}..
        /// </summary>
        public static string NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UM_X1 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UM_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível excluir uma {0} associada a uma {1}..
        /// </summary>
        public static string NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UMA_X1 {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_EXCLUIR_UMA_X0_ASSOCIADA_A_UMA_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} deve ser maior ou igual a {1}..
        /// </summary>
        public static string O_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1 {
            get {
                return ResourceManager.GetString("O_X0_DEVE_SER_MAIOR_OU_IGUAL_A_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto {0} é obrigatório..
        /// </summary>
        public static string OBJETO_X0_E_OBRIGATORIO {
            get {
                return ResourceManager.GetString("OBJETO_X0_E_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso..
        /// </summary>
        public static string OPERACAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("OPERACAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatória..
        /// </summary>
        public static string X0_E_OBRIGATORIA {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatória e deve conter {1} caracteres..
        /// </summary>
        public static string X0_E_OBRIGATORIA_E_DEVE_CONTER_X1_CARACTERES {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIA_E_DEVE_CONTER_X1_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório..
        /// </summary>
        public static string X0_E_OBRIGATORIO {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório e deve conter {1} caracteres..
        /// </summary>
        public static string X0_E_OBRIGATORIO_E_DEVE_CONTER_X1_CARACTERES {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO_E_DEVE_CONTER_X1_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválida..
        /// </summary>
        public static string X0_INVALIDA {
            get {
                return ResourceManager.GetString("X0_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} inválido..
        /// </summary>
        public static string X0_INVALIDO {
            get {
                return ResourceManager.GetString("X0_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não informado..
        /// </summary>
        public static string X0_NAO_INFORMADO {
            get {
                return ResourceManager.GetString("X0_NAO_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatória e deve conter entre {1} e {2} caracteres..
        /// </summary>
        public static string X0_OBRIGATORIA_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES {
            get {
                return ResourceManager.GetString("X0_OBRIGATORIA_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório e deve conter entre {1} e {2} caracteres..
        /// </summary>
        public static string X0_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES {
            get {
                return ResourceManager.GetString("X0_OBRIGATORIO_E_DEVE_CONTER_ENTRE_X1_E_X2_CARACTERES", resourceCulture);
            }
        }
    }
}
